budget_tracker/accounts/urls.py
from django.urls import path, include

from budget_tracker.accounts.views import AccountCreateView, login_user, logout_user, change_currency, \
    show_profile_details, delete_profile_photo, AccountDeleteView, delete_user_data

app_name = 'accounts'

urlpatterns = [
    path('auth/', include([
        path('account-create/', AccountCreateView.as_view(), name='create-account'),
        path('login/', login_user, name='login-account')
    ])),
    path('logout/', logout_user, name='logout-account'),
    path('<int:pk>/profile/', show_profile_details, name='details-profile'),
    path('<int:pk>/profile/photo-delete/', delete_profile_photo, name='delete-profile-photo'),
    path('<int:pk>/profile/currency/', change_currency, name='change-currency'),
    path('<int:pk>/account-delete/', AccountDeleteView.as_view(), name='delete-account'),
    path('<int:pk>/account-delete/delete/', delete_user_data, name='delete-user-data'),
]

budget_tracker/common/urls.py
from django.urls import path

from budget_tracker.common.views import IndexView, show_balance, show_dashboard

app_name = 'common'

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('dashboard/', show_dashboard, name='dashboard'),
    path('balance/', show_balance, name='balance'),
]

budget_tracker/expenses/urls.py
from django.urls import path

from budget_tracker.expenses.views import ExpenseListView, add_expense, delete_expense

app_name = 'expenses'

urlpatterns = [
        path('', ExpenseListView.as_view(), name='all-expenses'),
        path('add/', add_expense, name='add-expense'),
        path('delete/<int:pk>/', delete_expense, name='delete-expense'),
]

budget_tracker/income/urls.py
from django.urls import path

from budget_tracker.income.views import IncomeListView, add_income, delete_income, IncomeByTypeListView, \
    IncomeByCurrentMonthListView, IncomeUpdateView

app_name = 'income'

urlpatterns = [
    path('all/', IncomeListView.as_view(), name='all-income'),
    path('add/', add_income, name='add-income'),
    path('<int:pk>/delete/', delete_income, name='delete-income'),
    path('<int:pk>/edit/', IncomeUpdateView.as_view(), name='edit-income'),
    path('current-month/', IncomeByCurrentMonthListView.as_view(), name='current-month-income'),
    path('<str:type>/', IncomeByTypeListView.as_view(), name='earned-income'),
    path('<str:type>/', IncomeByTypeListView.as_view(), name='passive-income'),
    path('<str:type>/', IncomeByTypeListView.as_view(), name='portfolio-income'),
]

budget_tracker/urls.py
"""
URL configuration for budget_tracker project.
"""
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from budget_tracker import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('budget_tracker.common.urls')),
    path('users/', include('budget_tracker.accounts.urls')),
    path('income/', include('budget_tracker.income.urls')),
    path('expenses/', include('budget_tracker.expenses.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

budget_tracker/common/models.py
from django.db import models

budget_tracker/common/forms.py
from django import forms

budget_tracker/common/views.py
from django.db.models import Sum
from django.shortcuts import render
from django.views import generic as views

from budget_tracker.core.accounts_utils import get_user_profile
from budget_tracker.core.common_utils import get_recent_transactions, get_primary_chart_data, get_secondary_chart_data
from budget_tracker.core.currencies_utils import get_current_currency


class IndexView(views.TemplateView):
    template_name = 'common/index.html'


def show_dashboard(request):
    profile = get_user_profile(request)
    months, income_amounts, expense_amounts = get_primary_chart_data(profile)
    months, earned_income, passive_income = get_secondary_chart_data(profile)

    labels = months
    data = [int(amount) for amount in income_amounts]
    data2 = [int(amount) for amount in expense_amounts]
    currency = get_current_currency(request)

    earned_income_data = [int(amount) for amount in earned_income]
    passive_income_data = [int(amount) for amount in passive_income]

    all_income_sum = sum(income_amounts)
    all_expense_sum = sum(expense_amounts)

    context = {
        'labels': labels,
        'data': data,
        'data2': data2,
        'currency': currency,
        'earned_income_data': earned_income_data,
        'passive_income_data': passive_income_data,
        'all_income_sum': all_income_sum,
        'all_expense_sum': all_expense_sum,
    }

    return render(request, 'common/dashboard.html', context)


def show_balance(request):
    profile = get_user_profile(request)
    balance = profile.balance
    transactions = get_recent_transactions(profile)
    context = {
        'balance': balance,
        'transactions': transactions
    }

    return render(request,'common/balance-page.html', context)

budget_tracker/common/templates/common/balance-page.html
{% extends 'base.html' %}

{% block title %} Your Current Balance {% endblock %}

{% block content %}
    <div class="card-element">
        <h1>Current Balance</h1>
        <div class="balance-container">
            <h2>{{ balance.currency|make_list|first }}{{ balance.amount }}</h2>
            <p>Total Balance</p>
        </div>
        <div class="recent-transactions-container">
            <h2>Recent Transactions</h2>
            {% for transaction in transactions %}
                <div class="recent-transaction">
                    {% if transaction.source %}
                        <span><i class="fa-solid fa-plus"></i></span>
                    {% else %}
                        <span><i class="fa-solid fa-minus"></i></span>
                    {% endif %}
                    <i class="fa-regular fa-credit-card"></i>
                    <div>
                        <p class="recent-transaction-amount">
                            {{ transaction.currency|make_list|first }}{{ transaction.amount }}
                        </p>
                        <p class="recent-transaction-date">
                            {{ transaction.date|date:"F j" }}
                        </p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

budget_tracker/common/templates/common/dashboard.html
{% extends 'base.html' %}

{% block title %} Your Financial Overview {% endblock %}

{% block content %}
    <div class="dashboard-container">
        <div id="chart-container">
            <div class="bar-chart">
                <canvas id="bar-chart"></canvas>
            </div>
            <div class="secondary-chart">
                <canvas id="secondary-chart"></canvas>
            </div>
        </div>
        <div class="summary-container">
            <h2>Financial Summary:</h2>
            <p>Income: {{ all_income_sum }} {{ currency|make_list|first }}</p>
            <p>Expense: {{ all_expense_sum }} {{ currency|make_list|first }}</p>
            <section class="logged-in-choices">
                <h3>What do you want to do?</h3>
                <div class="dashboard-buttons">
                    <div>
                        <a href="{% url 'income:add-income' %}" class="button dashboard-button">Add an income</a>
                        <i class="fa-solid fa-arrow-right"></i>
                    </div>
                    <div>
                        <a href="{% url 'expenses:add-expense' %}" class="button dashboard-button">Add an expense</a>
                        <i class="fa-solid fa-arrow-right"></i>
                    </div>
                    <div>
                        <a href="{% url 'common:balance' %}" class="button dashboard-button">See your balance</a>
                        <i class="fa-solid fa-arrow-right"></i>
                    </div>
                </div>
            </section>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <script>
        let ctx = document.getElementById("bar-chart").getContext("2d");

        let chart = new Chart(ctx, {
            type: "bar",
            data: {
                labels: {{ labels|safe }},
                datasets: [
                    {
                        label: "Gross income ({{ currency|safe }})",
                        backgroundColor: [
                            "#79AEC8",
                        ],
                        borderColor: "#417690",
                        borderRadius: 12,
                        data: {{ data|safe }},
                        barThickness: 80,
                    },
                    {
                        label: "Gross expense ({{ currency|safe }})",
                        backgroundColor: [
                            "#85ce5b",
                        ],
                        borderColor: "#417690",
                        borderRadius: 12,
                        data: {{ data2|safe }},
                        barThickness: 80,
                    }
                ]
            },
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'top'
                    },
                    title: {
                        display: true,
                        text: 'Income and expenses over time'
                    }
                }
            }
        });

        let ctx_2 = document.getElementById("secondary-chart").getContext("2d");

        let chart_2 = new Chart(ctx_2, {
            type: "bar",
            data: {
                labels: {{ labels|safe }},
                datasets: [
                    {
                        label: "Earned income ({{ currency|safe }})",
                        backgroundColor: [
                            "#4865d8",
                        ],
                        borderColor: "#417690",
                        borderRadius: 12,
                        data: {{ earned_income_data|safe }},
                        barThickness: 80,
                    },
                    {
                        label: "Passive income ({{ currency|safe }})",
                        backgroundColor: [
                            "#79AEC8",
                        ],
                        borderColor: "#417690",
                        borderRadius: 12,
                        data: {{ passive_income_data|safe }},
                        barThickness: 80,
                    },
                ]
            },
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'top',
                    },
                    title: {
                        display: true,
                        text: 'Types of Income over time'
                    }
                }
            }
        });
    </script>
{% endblock %}

budget_tracker/common/templates/common/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Budget Tracker - A finance tracking helper {% endblock %}

{% block content %}
    <div class="landing-page-container">
        <h1 class="landing-heading">
            Welcome to BudgetTracker - Your Personal Finance Companion
        </h1>
        <section>
            <p>Manage your finances with the ultimate budget tracking app designed for simplicity and power.</p>
            <p>Take control of your money, track your income and expenses, and achieve financial freedom.</p>
        </section>

        <h2 class="features-heading">Some of our key features are:</h2>
        <section class="features-section">
            <ul class="key-features-list">
                <li>
                    <h3>Real-Time Overview</h3>
                    <p>Instantly see your financial health with a glance. Our intuitive dashboard displays your current
                        balance, income, and expenses in real-time.</p>
                    <img src="{% static 'images/admin-dashboard-chart-example.PNG' %}" alt="dashboard-image">
                </li>
                <li>
                    <h3>Easy Expense Tracking</h3>
                    <p>Effortlessly log your daily expenses with a few clicks.
                        Stay organized and gain insights into your spending patterns.</p>
                </li>
                <li>
                    <h3>Income Tracking</h3>
                    <p> Never miss a payday! Keep tabs on your income sources and monitor your overall cash flow.</p>
                </li>
            </ul>
        </section>

        <h2 class="choose-heading">Why Choose BudgetTracker?</h2>
        <section class="choose-section">
            <ul class="choose-list">
                <li>
                    <h3>User-Friendly Interface</h3>
                    <p>Navigate with ease and enjoy a seamless user experience,
                        whether you're a financial pro or just starting your budgeting journey.</p>
                    <p class="income-example-img">
                        <img src="{% static 'images/admin-income-example.PNG' %}" alt="income-page-example-pic">
                    </p>
                </li>
                <li>
                    <h3>Save Time, Save Money</h3>
                    <p> BudgetTracker simplifies money management, saving you time and helping you make informed decisions
                        that lead to financial savings.</p>
                </li>
            </ul>
        </section>

        <section class="get-started-section">
            <h3>Get started today!</h3>
            <p>Sign up now and embark on a journey to financial well-being.</p>
            <a href="{% url 'accounts:create-account' %}" class="button get-started-btn">Get Started</a>
        </section>
    </div>
{% endblock %}