budget_tracker/accounts/urls.py
from django.urls import path, include

from budget_tracker.accounts.views import AccountCreateView, login_user, logout_user, change_currency, \
    show_profile_details, delete_profile_photo, AccountDeleteView, delete_user_data

app_name = 'accounts'

urlpatterns = [
    path('auth/', include([
        path('account-create/', AccountCreateView.as_view(), name='create-account'),
        path('login/', login_user, name='login-account')
    ])),
    path('logout/', logout_user, name='logout-account'),
    path('<int:pk>/profile/', show_profile_details, name='details-profile'),
    path('<int:pk>/profile/photo-delete/', delete_profile_photo, name='delete-profile-photo'),
    path('<int:pk>/profile/currency/', change_currency, name='change-currency'),
    path('<int:pk>/account-delete/', AccountDeleteView.as_view(), name='delete-account'),
    path('<int:pk>/account-delete/delete/', delete_user_data, name='delete-user-data'),
]

budget_tracker/common/urls.py
from django.urls import path

from budget_tracker.common.views import IndexView, show_balance, show_dashboard

app_name = 'common'

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('dashboard/', show_dashboard, name='dashboard'),
    path('balance/', show_balance, name='balance'),
]

budget_tracker/expenses/urls.py
from django.urls import path

from budget_tracker.expenses.views import ExpenseListView, add_expense, delete_expense

app_name = 'expenses'

urlpatterns = [
        path('', ExpenseListView.as_view(), name='all-expenses'),
        path('add/', add_expense, name='add-expense'),
        path('delete/<int:pk>/', delete_expense, name='delete-expense'),
]

budget_tracker/income/urls.py
from django.urls import path

from budget_tracker.income.views import IncomeListView, add_income, delete_income, IncomeByTypeListView, \
    IncomeByCurrentMonthListView, IncomeUpdateView

app_name = 'income'

urlpatterns = [
    path('all/', IncomeListView.as_view(), name='all-income'),
    path('add/', add_income, name='add-income'),
    path('<int:pk>/delete/', delete_income, name='delete-income'),
    path('<int:pk>/edit/', IncomeUpdateView.as_view(), name='edit-income'),
    path('current-month/', IncomeByCurrentMonthListView.as_view(), name='current-month-income'),
    path('<str:type>/', IncomeByTypeListView.as_view(), name='earned-income'),
    path('<str:type>/', IncomeByTypeListView.as_view(), name='passive-income'),
    path('<str:type>/', IncomeByTypeListView.as_view(), name='portfolio-income'),
]

budget_tracker/urls.py
"""
URL configuration for budget_tracker project.
"""
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from budget_tracker import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('budget_tracker.common.urls')),
    path('users/', include('budget_tracker.accounts.urls')),
    path('income/', include('budget_tracker.income.urls')),
    path('expenses/', include('budget_tracker.expenses.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/navbar.html
<nav>
    {% if not request.user.is_authenticated %}
        <ul>
            <li>
                <a href="{% url 'common:home' %}">
                    Home
                </a>
            </li>
            <li>
                <a href="{% url 'accounts:create-account' %}">
                    Sign Up
                </a>
            </li>
            <li>
                <span> or </span>
            </li>
            <li>
                <a href="{% url 'accounts:login-account' %}">
                    Sign In
                </a>
            </li>
            <li>
                <a href="#">
                    About
                </a>
            </li>
        </ul>

    {% else %}
        <ul class="logged-in-list">
            <li>
                <a href="{% url 'common:dashboard' %}">
                    Dashboard
                </a>
            </li>
            <li>
                <a href="{% url 'accounts:details-profile' request.user.pk %}">
                    Profile
                </a>
            </li>
            <li>
                <a href="{% url 'income:all-income' %}" class="content-nav-link">
                    Income
                </a>
            </li>
            <li>
                <a href="{% url 'expenses:all-expenses' %}" class="content-nav-link">
                    Expenses
                </a>
            </li>
            <li>
                <a href="{% url 'common:balance' %}">
                    Balance
                </a>
            </li>
            {% if request.context_variable %}
                <li class="nav-profile-photo">
                    <img src="{{ request.context_variable.photo.url }}" alt="photo">
                </li>
            {% endif %}
            <li class="sign-out">
                <a href="{% url 'accounts:logout-account' %}">
                    Sign Out
                </a>
            </li>
        </ul>
    {% endif %}
</nav>