budget_tracker/accounts/urls.py
from django.urls import path, include

from budget_tracker.accounts.views import AccountCreateView, login_user, logout_user, change_currency, \
    show_profile_details, delete_profile_photo, AccountDeleteView, delete_user_data

app_name = 'accounts'

urlpatterns = [
    path('auth/', include([
        path('account-create/', AccountCreateView.as_view(), name='create-account'),
        path('login/', login_user, name='login-account')
    ])),
    path('logout/', logout_user, name='logout-account'),
    path('<int:pk>/profile/', show_profile_details, name='details-profile'),
    path('<int:pk>/profile/photo-delete/', delete_profile_photo, name='delete-profile-photo'),
    path('<int:pk>/profile/currency/', change_currency, name='change-currency'),
    path('<int:pk>/account-delete/', AccountDeleteView.as_view(), name='delete-account'),
    path('<int:pk>/account-delete/delete/', delete_user_data, name='delete-user-data'),
]

budget_tracker/common/urls.py
from django.urls import path

from budget_tracker.common.views import IndexView, show_balance, show_dashboard

app_name = 'common'

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('dashboard/', show_dashboard, name='dashboard'),
    path('balance/', show_balance, name='balance'),
]

budget_tracker/urls.py
"""
URL configuration for budget_tracker project.
"""
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from budget_tracker import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('budget_tracker.common.urls')),
    path('users/', include('budget_tracker.accounts.urls')),
    path('income/', include('budget_tracker.income.urls')),
    path('expenses/', include('budget_tracker.expenses.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

budget_tracker/accounts/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser

from budget_tracker.accounts.validators import validate_name_contains_only_letters, \
    validate_name_starts_with_capital_letter


class MyCustomUserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password=None):
        if not email:
            raise ValueError("Users must have an email address")

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password=None):
        user = self.create_user(
            email,
            password=password,
            first_name=first_name,
            last_name=last_name
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class BudgetTrackerUser(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True, blank=False, null=False)

    first_name = models.CharField(max_length=50,
                                  validators=[
                                        validate_name_contains_only_letters,
                                        validate_name_starts_with_capital_letter,
                                        MinLengthValidator(3, message='A name must contain at least 3 letters'),
                                  ],
                                  blank=False, null=False)

    last_name = models.CharField(max_length=50,
                                 validators=[
                                     validate_name_contains_only_letters,
                                     validate_name_starts_with_capital_letter,
                                     MinLengthValidator(3, message='A name must contain at least 3 letters'),
                                 ],
                                 blank=False, null=False)

    is_active = models.BooleanField(default=True)

    is_admin = models.BooleanField(default=False)

    objects = MyCustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return self.email

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'

    def get_short_name(self):
        return self.first_name

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin


UserModel = get_user_model()


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return f'user_{instance.user_profile.user.pk}/{filename}'


class UserProfile(models.Model):
    user = models.OneToOneField(UserModel, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user)


class Currency(models.Model):
    EURO = '€ EUR'
    DOLLAR = '$ USD'
    BRITISH_POUND = '£ GBP'
    BULGARIAN_LEV = 'лв BGN'

    CURRENCY_CHOICES = (
        (EURO, EURO),
        (DOLLAR, DOLLAR),
        (BRITISH_POUND, BRITISH_POUND),
        (BULGARIAN_LEV, BULGARIAN_LEV),
    )

    user_profile = models.OneToOneField(UserProfile, on_delete=models.CASCADE)

    currency = models.CharField(
        choices=CURRENCY_CHOICES,
        default=EURO,
        null=False,
        blank=False
    )

    class Meta:
        verbose_name_plural = 'Currencies'

    def __str__(self):
        return self.currency


class Balance(models.Model):
    user_profile = models.OneToOneField(UserProfile, on_delete=models.CASCADE)

    amount = models.DecimalField(
        max_digits=10, decimal_places=2,
        null=False, blank=False
    )

    currency = models.CharField(max_length=10, null=False, blank=False)

    class Meta:
        verbose_name_plural = 'Balance'

    def __str__(self):
        return f'{self.currency} {self.amount}'

    def save(self, *args, **kwargs):
        if self.amount < 0:
            self.amount = 0
        super(Balance, self).save(*args, **kwargs)


class ProfilePhoto(models.Model):
    user_profile = models.OneToOneField(UserProfile, on_delete=models.CASCADE)

    photo = models.ImageField(upload_to=user_directory_path, null=True, blank=True)

    def __str__(self):
        return f'Photo of {self.user_profile}'

budget_tracker/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError

from budget_tracker.accounts.models import Currency, UserProfile, ProfilePhoto
from budget_tracker.core.currencies_utils import get_current_currency

UserModel = get_user_model()


class AccountsBaseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-input registration-form-input'

    class Meta:
        model = UserModel
        fields = ('first_name', 'last_name', 'email', 'password')

        widgets = {
            'first_name': forms.TextInput(
                attrs={
                    'placeholder': 'First name',

                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'placeholder': 'Last name',
                }
            ),
            'email': forms.EmailInput(
                attrs={
                    'placeholder': 'Email',
                }
            ),
            'password': forms.PasswordInput(
                attrs={
                    'placeholder': 'Password',
                }
            )
        }


class RegistrationForm(AccountsBaseForm):

    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'placeholder': 'Confirm Password'}),
        label='Password')

    def clean_password2(self):
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password and password2 and password != password2:
            raise ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class LoginForm(AccountsBaseForm):
    class Meta(AccountsBaseForm.Meta):
        fields = ('email', 'password')


class ProfilePhotoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'photo-input'

    class Meta:
        model = ProfilePhoto
        fields = ('photo',)

        labels = {'photo': 'Upload Photo'}


class CurrencyForm(forms.ModelForm):
    def __init__(self, request, *args, **kwargs):
        self.request = request
        super().__init__(*args, **kwargs)
        user_currency = get_current_currency(self.request)
        self.fields['currency'].initial = user_currency

    class Meta:
        model = Currency
        fields = ('currency',)

        widgets = {
            'currency': forms.Select(
                attrs={
                    'class': 'form-input currency-form-input'
                }
            )
        }

budget_tracker/accounts/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic as views

from budget_tracker.accounts.forms import RegistrationForm, LoginForm, CurrencyForm, ProfilePhotoForm
from budget_tracker.accounts.models import Currency, ProfilePhoto
from budget_tracker.core.accounts_utils import get_user_profile, get_profile_photo
from budget_tracker.core.common_utils import get_current_balance
from budget_tracker.core.currencies_utils import change_existing_currency, get_current_currency

UserModel = get_user_model()


class AccountCreateView(SuccessMessageMixin, views.CreateView):
    model = UserModel
    template_name = 'accounts/account-create-page.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('accounts:login-account')

    success_message = 'Your account was created. You can log in.'


def login_user(request):
    if request.method == 'GET':
        login_form = LoginForm()
    else:
        login_form = LoginForm(request.POST)
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('common:dashboard')
        else:
            messages.error(request, 'Invalid email or password. '
                                    'Please try again.')
    return render(
        request,
        'accounts/account-login-page.html',
        {'form': login_form}
    )


def logout_user(request):
    logout(request)
    return redirect('common:home')


def show_profile_details(request, pk):
    profile = get_user_profile(request)
    if request.method == 'POST':
        form = ProfilePhotoForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            previous_photo = get_profile_photo(profile)
            if previous_photo is not None:
                previous_photo.delete()
            form.user_profile = profile
            form.save()
            return redirect('accounts:details-profile', pk)
    form = ProfilePhotoForm()

    photo = get_profile_photo(profile)
    balance = get_current_balance(profile)
    context = {
        'form': form,
        'profile': profile,
        'photo': photo,
        'balance': balance,
    }
    return render(
        request,
        'accounts/account-details-page.html',
        context
    )


def delete_profile_photo(request, pk):
    profile = get_user_profile(request)
    photo = ProfilePhoto.objects.filter(user_profile=profile).get()
    photo.delete()
    return redirect('accounts:details-profile', pk)


def change_currency(request, pk):
    user_profile = get_user_profile(request)

    if request.method == 'POST':
        currency_form = CurrencyForm(request, request.POST)
        if currency_form.is_valid():
            new_currency = currency_form.save(commit=False)
            has_old_currency = Currency.objects.filter(user_profile=user_profile).exists()

            if has_old_currency:
                change_existing_currency(user_profile, new_currency)
            new_currency.save()
            return redirect(request.META['HTTP_REFERER'])

    currency_form = CurrencyForm(request)
    current_currency = get_current_currency(request)
    context = {
        'form': currency_form,
        'currency': current_currency
    }

    return render(
        request,
        'currencies/currency-change-page.html',
        context
    )


class AccountDeleteView(views.TemplateView):
    template_name = 'accounts/account-delete-page.html'


def delete_user_data(request, pk):
    current_user = UserModel.objects.filter(pk=pk).get()
    current_user.delete()
    return redirect('common:home')

budget_tracker/accounts/templates/accounts/account-create-page.html
{% extends 'base.html' %}

{% block title %} Budget Tracker - Account Creation {% endblock %}

{% block content %}
    <h2 class="heading registration-heading">Create your account</h2>
    
    <div class="centered-container registration-container form-container">
        <form action="{% url 'accounts:create-account' %}" method="post">
            {% for field in form %}
                <div class="form-label reg-form-label">
                    {{ field.label }}
                </div>
                <div class="reg-form-div">
                    {{ field }}
                </div>
            {% endfor %}
            <button type="submit" class="register-continue-btn">Continue</button>
            {% csrf_token %}
            <div class="login-info-div">
                <p>Have an account? 
                    <a href="{% url 'accounts:login-account' %}" class="login-extra-link">Sign in</a>
                </p>
            </div>
            {% if form.errors %}
                <div class="registration-errors form-errors">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                </div>
            {% endif %}
        </form>
    </div>
{% endblock %}

budget_tracker/accounts/templates/accounts/account-delete-page.html
{% extends 'base.html'%}

{% block title %} Account Delete Confirmation {% endblock %}

{% block content %}
    <h2 class="heading account-delete-heading">
        Are you sure you want to delete your account?
    </h2>
    <p class="account-termination">
        Account termination is irreversible and all data will be lost
    </p>
    <div class="account-delete-buttons">
        <a href="{% url 'common:dashboard' %}" class="button get-back-btn">
            No, get me back
        </a>
        <a href="{% url 'accounts:delete-user-data' request.user.pk %}" class="button delete-all-data-btn">
            Delete everything
        </a>
    </div>
{% endblock %}

budget_tracker/accounts/templates/accounts/account-details-page.html
{% extends 'base.html' %}
{% load static %}

{% block title %} BudgetTracker - Profile {% endblock %}

{% block content %}
    <h2 class="heading profile-heading">Your Profile</h2>

    <div class="centered-container profile-container">
        <div class="profile-info-container">
            <div class="profile-names">
                <h3>{{ user.first_name }} <br> {{ user.last_name }}</h3>
                <br>
                <h3>{{ user.email }}</h3>
                <br>
                <h3>Balance: {{ balance }}</h3>
            </div>
            <div class="profile-photo">
                {% if photo %}
                    <img src="{{ photo.photo.url }}" alt="profile-pic">
                {% else %}
                    <p>Your Profile Photo</p>
                {% endif %}
            </div>
        </div>
        <div class="remove-photo">
            {% if photo %}
                <a href="{% url 'accounts:delete-profile-photo' user.pk %}">Remove Photo</a>
            {% endif %}
        </div>
        <div class="profile-photo-form">
            <form method="post" enctype="multipart/form-data">
                {% for field in form %}
                    <div class="form-label profile-form-label">
                        {{ field.label_tag }}
                    </div>
                    <div class="profile-form-div">
                        {{ field }}
                    </div>
                {% endfor %}
                <div class="profile-buttons">
                    <button type="submit" class="profile-save-button">Save</button>
                </div>
                {% csrf_token %}
            </form>
        </div>
        <div class="profile-links">
            <a href="#">Change password</a>
            <a href="{% url 'accounts:change-currency' user.pk %}">Change currency</a>
            {% if photo %}
                <a href="#" class="change-photo-link">Change photo</a>
            {% endif %}
        </div>
        <a href="{% url 'accounts:delete-account' user.pk %}" class="account-delete-button">Delete Account</a>
    </div>
    <script src="{% static 'js/profile-photo-script.js' %}"> </script>
{% endblock %}

budget_tracker/accounts/templates/accounts/account-login-page.html
{% extends 'base.html' %}

{% block title %} Budget Tracker - Account Login {% endblock %}

{% block content %}
    <h2 class="heading login-heading">Log into your account</h2>

    <div class="centered-container login-container">
        <form action="{% url 'accounts:login-account' %}" method="post">
            {% for field in form %}
                <div class="form-label login-label">
                    {{ field.label }}
                </div>
                <div class="login-field-div">
                    {{ field }}
                </div>
            {% endfor %}
            <button type="submit" class="login-button">Enter</button>
            {% csrf_token %}
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    <div class="registration-success-message">
                        {{ message }}
                    </div>
                {% else %}
                    <div class="login-errors form-errors">
                        {{ message }}
                    </div>
                {% endif %}
            {% endfor %}
        </form>
    </div>
{% endblock %}