budget_tracker/income/urls.py
from django.urls import path

from budget_tracker.income.views import IncomeListView, add_income, delete_income, IncomeByTypeListView, \
    IncomeByCurrentMonthListView, IncomeUpdateView

app_name = 'income'

urlpatterns = [
    path('all/', IncomeListView.as_view(), name='all-income'),
    path('add/', add_income, name='add-income'),
    path('<int:pk>/delete/', delete_income, name='delete-income'),
    path('<int:pk>/edit/', IncomeUpdateView.as_view(), name='edit-income'),
    path('current-month/', IncomeByCurrentMonthListView.as_view(), name='current-month-income'),
    path('<str:type>/', IncomeByTypeListView.as_view(), name='earned-income'),
    path('<str:type>/', IncomeByTypeListView.as_view(), name='passive-income'),
    path('<str:type>/', IncomeByTypeListView.as_view(), name='portfolio-income'),
]

budget_tracker/urls.py
"""
URL configuration for budget_tracker project.
"""
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from budget_tracker import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('budget_tracker.common.urls')),
    path('users/', include('budget_tracker.accounts.urls')),
    path('income/', include('budget_tracker.income.urls')),
    path('expenses/', include('budget_tracker.expenses.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

budget_tracker/income/models.py
from django.core.validators import MinValueValidator, MinLengthValidator
from django.db import models
from datetime import date

from budget_tracker.accounts.models import UserProfile, Currency
from budget_tracker.income.validators import validate_income_source_contains_only_letters


class Income(models.Model):

    MAX_LEN_INCOME_SOURCE = 30
    MIN_LEN_INCOME_SOURCE = 4
    MIN_AMOUNT = 5
    MAX_LEN_TYPE = 25
    MAX_LEN_CURRENCY = 10

    EARNED_INCOME = 'Earned Income'
    PASSIVE_INCOME = 'Passive Income'
    PORTFOLIO_INCOME = 'Portfolio Income'

    INCOME_CHOICES = (
        (EARNED_INCOME, EARNED_INCOME),
        (PASSIVE_INCOME, PASSIVE_INCOME),
        (PORTFOLIO_INCOME, PORTFOLIO_INCOME),
    )

    income_source_error_message = f'Income source must contain at least {MIN_LEN_INCOME_SOURCE} characters'
    amount_error_message = f'Minimum amount must be at least {MIN_AMOUNT}'

    source = models.CharField(max_length=MAX_LEN_INCOME_SOURCE,
                              validators=[MinLengthValidator(MIN_LEN_INCOME_SOURCE,
                                                             message=income_source_error_message),
                                          validate_income_source_contains_only_letters],
                              null=False, blank=False)

    amount = models.DecimalField(max_digits=10, decimal_places=2,
                                 validators=[MinValueValidator(MIN_AMOUNT, message=amount_error_message)],
                                 null=False, blank=False)

    type = models.CharField(max_length=MAX_LEN_TYPE, choices=INCOME_CHOICES, null=False, blank=False)

    currency = models.CharField(max_length=MAX_LEN_CURRENCY, null=True, blank=True)

    date = models.DateField(default=date.today, null=False, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return f'Income - {self.amount}{self.currency} - {self.date}'

budget_tracker/income/forms.py
from django import forms

from budget_tracker.income.models import Income


class IncomeBaseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-input income-form-input'

    class Meta:
        model = Income
        fields = ('source', 'amount', 'type')

        labels = {
            'source': 'Source of Income:',
            'amount': 'Amount:',
            'type': 'Type of Income:',
        }


class IncomeAddForm(IncomeBaseForm):
    pass


class IncomeUpdateForm(IncomeBaseForm):
    pass

budget_tracker/income/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic as views

from budget_tracker.core.accounts_utils import get_user_profile
from budget_tracker.core.common_utils import add_to_balance, subtract_from_balance, get_current_month
from budget_tracker.core.currencies_utils import get_current_currency
from budget_tracker.core.mixins import IncomeListContextMixin
from budget_tracker.income.forms import IncomeAddForm, IncomeUpdateForm
from budget_tracker.income.models import Income


class IncomeListView(IncomeListContextMixin, views.ListView):
    model = Income
    template_name = 'income/income-list-page.html'

    def get_queryset(self):
        user_profile = get_user_profile(self.request)
        self.queryset = user_profile.income_set.all().order_by('date')
        return super().get_queryset()


class IncomeByTypeListView(views.ListView):
    model = Income
    template_name = 'income/income-list-page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_currency'] = get_current_currency(self.request)
        return context

    def get_queryset(self):
        user_profile = get_user_profile(self.request)
        income_type = self.kwargs['type']
        self.queryset = user_profile.income_set.filter(type=income_type)
        return self.queryset


class IncomeByCurrentMonthListView(IncomeListContextMixin, views.ListView):
    model = Income
    template_name = 'income/income-list-page.html'

    def get_queryset(self):
        user_profile = get_user_profile(self.request)
        current_month = get_current_month()
        self.queryset = user_profile.income_set.filter(date__month=current_month)
        return self.queryset


def add_income(request):
    current_currency = get_current_currency(request)
    user_profile = get_user_profile(request)

    if request.method == 'POST':
        form = IncomeAddForm(request.POST)
        if form.is_valid():
            income = form.save(commit=False)
            income.profile = user_profile
            income.currency = current_currency
            income.save()
            add_to_balance(user_profile, income.amount)
            return redirect('income:all-income')
    form = IncomeAddForm()
    return render(request, 'income/income-add-page.html', {
        'form': form, 'current_currency': current_currency
    })


class IncomeUpdateView(views.UpdateView):
    model = Income
    form_class = IncomeUpdateForm
    template_name = 'income/income-edit-page.html'
    success_url = reverse_lazy('income:all-income')


def delete_income(request, pk):
    user_profile = get_user_profile(request)
    income = user_profile.income_set.filter(pk=pk).get()
    subtract_from_balance(user_profile, income.amount)
    income.delete()
    return redirect('income:all-income')

budget_tracker/income/templates/income/income-add-page.html
{% extends 'base.html' %}

{% block title %} Add Source of Income {% endblock %}]

{% block content %}
    <h2 class="heading add-income-heading">Log new income</h2>

    <div class="add-income-container">
        <p><i class="fa-solid fa-coins"></i></p>

        <form action="{% url 'income:add-income' %}" method="post">
            <div>
                <label>{{ form.source.label }}</label>
                {{ form.source }}
            </div>
            <div>
                <label>{{ form.amount.label }}</label>
                <div class="amount-and-currency">
                    <span>{{ form.amount }}</span><span>{{ current_currency|make_list|first }}</span>
                </div>
            </div>
            <div>
                <label>{{ form.type.label }}</label>
                {{ form.type }}
            </div>
            <button type="submit">Add</button>
            {% csrf_token %}
            {% if form.errors %}
                <div class="form-errors">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                </div>
            {% endif %}
        </form>
    </div>
{% endblock %}

budget_tracker/income/templates/income/income-edit-page.html
{% extends 'base.html' %}

{% block title %} Edit an Income {% endblock %}

{% block content %}
    <h2 class="heading">Edit income</h2>

    <div class="edit-income-container">
        <p><i class="fa-solid fa-pen-to-square"></i></p>

        <form action="{% url 'income:edit-income' object.pk %}" method="post">
            <div>
                <label>{{ form.source.label_tag }}</label>
                {{ form.source }}
            </div>

            <div>
                <label>{{ form.amount.label_tag }}</label>
                <div class="amount-and-currency">
                    <span>{{ form.amount }}</span> <span>{{ object.currency|make_list|first }}</span>
                </div>
            </div>

            <div>
                <label>{{ form.type.label_tag }}</label>
                {{ form.type }}
            </div>
            <button type="submit" class="edit-income-btn">Edit</button>
            {% csrf_token %}
        </form>
    </div>
{% endblock %}

budget_tracker/income/templates/income/income-list-page.html
{% extends 'base.html' %}

{% block title %} Income Tracking {% endblock %}

{% block content %}
    <h2 class="heading income-list-heading">Your currently logged income</h2>
    <div class="filters-container">
        <h3 class="filters-heading">Show only:</h3>
        <ul class="income-types-list">
            <li>
                <a href="{% url 'income:earned-income' 'Earned Income' %}">Earned Income</a>
            </li>
            <li>
                <a href="{% url 'income:passive-income' 'Passive Income' %}">Passive Income</a>
            </li>
            <li>
                <a href="{% url 'income:passive-income' 'Portfolio Income' %}">Portfolio Income</a>
            </li>
            <li>
                <a href="{% url 'income:current-month-income' %}">Current Month</a>
            </li>
        </ul>
        <p>
            <a href="{% url 'income:all-income' %}">Show all</a>
        </p>
    </div>
    <div class="income-container">
        <ul class="income-info-list">
            <li>
                <b>Source of income:</b>
            </li>
            <li>
                <b>Amount:</b>
            </li>
            <li>
                <b>Type:</b>
            </li>
            <li>
                <b>Submitted on:</b>
            </li>
            <li>
                <b>Remove: or Edit:</b>
            </li>
        </ul>
        {% for income in object_list %}
            <ul class="income-data-list">
                <li>
                    {{ income.source|capfirst }}
                </li>
                <li>
                    {{ income.amount }} {{ current_currency|make_list|first }}
                </li>
                <li>
                    {{ income.type }}
                </li>
                <li>
                    {{ income.date }}
                </li>
                <li>
                    <a href="{% url 'income:delete-income' income.pk %}"><i class="fa-solid fa-xmark"></i></a>
                    <a href="{% url 'income:edit-income' income.pk %}"
                       class="edit-income-link"><i class="fa-regular fa-pen-to-square"></i></a>
                </li>
            </ul>
        {% endfor %}
    </div>
    <a href="{% url 'income:add-income' %}" class="button add-income-button">Add more Income</a>
    <div class="income-calculations">
        <div class="highest-monthly-income">
            <h3>Highest income of the month is:</h3>
            <p>
                {{ highest_income.source|capfirst }} --- <strong>{{ highest_income.amount }}
                {{ current_currency|make_list|first }}</strong>
            </p>
        </div>
        <div class="total-monthly-income">
            <h3>Total income for this month:</h3>
            <p>
                <strong>{{ total_income }} {{ current_currency|make_list|first }}</strong>
            </p>
        </div>
    </div>
{% endblock %}